USE EMP;

--1) WHAT IS SEQUEL AND EXPLAIN HISTORY OF SEQUEL ?
--2) EXPLAIN DATA WITH EXAMPLE
--3) WHAT IS DATABASE  AND EXPLAIN IT ?
--4) WHAT DOES DBMS AND RDBMS EXPLAIN WITH DIFFERENCES ?
--5) EXPLAIN THE RULES OF AN E.F CODD ?
--6) WHAT IS DATATYPE AND EXPLAIN ALL THE DATATYPES WITH SYNTAX ?
--7) DIFFERENCES BETWEEN CHAR AND VARCHAR ?
--8) EXPLAIN CONSTRAINTS WITH SYNTAX FOR EACH CONSTRAINTS ?
--9) DIFFERENCES BETWEEN PRIMARY KEY AND FOREIGN KEY 
--10) DIFFERENCES BETWEEN UNIQUE AND DISTINCT ?

-- Create the table
CREATE TABLE DEPT (
    DEPTNO INT PRIMARY KEY,
    DNAME VARCHAR(20),
    LOC VARCHAR(20)
);

-- Insert the data
INSERT INTO DEPT (DEPTNO, DNAME, LOC) VALUES
(10, 'ACCOUNTING', 'NEW YORK'),
(20, 'RESEARCH', 'DALLAS'),
(30, 'SALES', 'CHICAGO'),
(40, 'OPERATIONS', 'BOSTON');

-- Verify the data
SELECT * FROM DEPT;


-->>>>>>> QUERIES ON PROJECTION >>>>>>>>>>

--11) WAQTD EMPLOYEES NAME FROM EMPLOYEES TABLE ?
SELECT ENAME
FROM EMP;

--12) WAQTD SAL AND EMPLOYEES NAME FROM EMPLOYEE TABLE ?
SELECT SAL , ENAME
FROM EMP;

--13) WAQTD NAME AND DEPTNO AND JOBS THAT ARE PRESENT IN EMP TABLE ?
SELECT ENAME , DEPTNO , JOB
FROM EMP;

--14) WAQTD HIREDATE AND DEPTNO FOR ALL THE EMPLOYEES ?
SELECT HIREDATE , DEPTNO
FROM EMP;

--15) WAQTD MGR AND EMPNO FROM EMPLOYEE TABLE ?
SELECT MGR , EMPNO
FROM EMP;

--16) WAQTD ALL THE DETAILS OF ALL THE EMPLOYEES ?
SELECT *
FROM EMP;

--17) WAQTD DEPARTMENT NAME FROM DEPT TABLE ?
SELECT DEPTNAME
FROM DEPT;

--18) WAQTD LOC THAT ARE PRESENT IN DEPT TABLE
SELECT LOC
FROM EMP;

--19) WAQTD DEPTNO AND LOC PRESENT IIN DEPT TABLE ?
SELECT DEPTNO , LOC
FROM EMP;

--20) WAQTD ALL THE DETAILS OF DEPT TABLE ? 
SELECT *
FROM EMP;

--21) WAQTD DIFFERENT JOBS PRESENT IN EMPLOYEE TABLE ?
SELECT DISTINCT JOB
FROM EMP;

--22) WAQTD ENAME AND SAL PRESENT IN EMP TABLE BUT THERE SHOULD NOT BE ANY REPEATED RECORDS ?
SELECT DISTINCT ENAME , SAL
FROM EMP;

--23) WAQTD HIREDATE AND SAL OF AN EMPLOYEES BUT THERE SHOULD NOT BE ANY REPEATED RECORDS ?
SELECT DISTINCT HIREDATE , SAL
FROM EMP;

--24) WAQTD JOB SAL AND DEPTNO OF AN EMPLOYEES BUT THERE SHOULD NOT BE ANY REPEATED RECORDS ?
SELECT DISTINCT JOB, SAL, DEPTNO
FROM EMP;

--25) WAQTD ALL THE DETAILS OF AN EMPLOYEES BUT THERE SHOULD NOT BE ANY REPEATED RECORDS ?
SELECT DISTINCT *
FROM EMP;

--26) WAQTD ANNUAL SALARY FOR ALL THE EMPLOYEES ?
SELECT SAL * 12 AS ANNUAL_SAL
FROM EMP;

--27) WAQTD HALF TERM SALARY FOR ALL THE EMPLOYEES ?
SELECT SAL * 6
FROM EMP;

--28) WAQTD ENAME AND ANNUAL SALARY FOR ALL THE EMPLOYEES ?
SELECT EMP.* , SAL*12 AS ANNUAL_SAL
FROM EMP;

--29) WAQTD DEPTNO JOB AND SAL WITH 10% HIKE FOR ALL THE EMPLOYEE ?
SELECT DEPTNO , JOB ,SAL , SAL+SAL*10/100
FROM EMP;

--30) WAQTD ALL THE DETAILS OF AN EMPLOYEES ALONG WITH ANNUAL SALARY ?
SELECT EMP.* , SAL*12 AS ANNUAL_SAL
FROM EMP;


--31) WAQTDALL THE DETAILS OF AN EMPLOYEES ALONG WITH 10% HIKE IN ANNUAL SALARY FOR ALL THE EMPLOYEE ?
SELECT EMP.* , (SAL+SAL*10/100)*12
FROM EMP;

--32) WAQTD SAL ANNAUL SALARY HALF_TERM SALARY AND QUERTER TERM SALARY FOR ALL THE EMPLOYEES ?
SELECT SAL, SAL*12 AS ANNUAL_SAL , SAL*6 AS HALF_TERM_SAL , SAL *3 AS QUARTER_TERM_SAL
FROM EMP;

--33) WAQTD ANNUAL SALARY WITH 20% DEDUCTION  FOR ALL THE EMPLOYEES ?
SELECT SAL*12 "ANNUAL SAL", (SAL-SAL*20/100)*12 "DEDUCTION SAL"
FROM EMP;

--34) WAQTD ALL THE DETAILS ALONG WITH 100 RS PENALTY FOR ALL THE EMPLOYEES ?
SELECT EMP.*, SAL+100 AS PENALTY
FROM EMP;

--35) WAQTD TOTAL SALARY NEEDED TO PAY FOR EACH AND EVERY EMPLOYEE ?
SELECT SAL + COMM AS TOTAL_SALARY
FROM EMP;

--36) WAQTD ANNAUL SALARY  AND HALF_TERM SALARY WITH ALIAS NAME FOR ALL THE EMPLOYEES ?
SELECT SAL *12 "ANNUAL SAL" , SAL * 6 "HALF SAL"
FROM EMP;

--37) WAQTD ALL THE DETAILS OF AN EMPLOYEES ALONG WITH 12% HIKE IN ANNUAL SALARY WITH ALIAS NAME FOR ALL THE EMPLOYEES 
SELECT EMP.* , (SAL+SAL*12/100)*12 "12% HIKE SAL"
FROM EMP;

--38) WAQTD JOB AS DESIGNATION HIREDATE AS JOINING DATE MGR AS REPORTING MANAGER NUMBER FOR ALL THE EMPLOYEES ?
SELECT JOB "DESIGNATION " , HIREDATE "JOINING DATE" , MGR AS "HIRING MANAGER"
FROM EMP;

--39) WAQTD JOB  WITH DEPTNO FOR ALL THE EMPLOYEES USING ALIAS AS DESIGNATION FOR THE JOB AND DNO FOR THE DEPTNO ?
SELECT JOB AS DESIGNATION , DEPTNO AS DNO
FROM EMP;

--40) WAQTD ALL THE DETAILS OF AN EMPLOYEES ALONG WITH 50 RS HIKE IN SAL USE ALIAS AS BONUS FOR ALL THE EMPLOYEE ?
SELECT EMP.* , SAL+SAL*50/100 AS BONUS
FROM EMP;


-->>>>>>>>>>> QUERIES ON SELECTION >>>>>>>>>>

--41 ) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHOSE SALARY IS MORE THEN 1000 ?
SELECT *
FROM EMP
WHERE SAL > 1000;

--42) WAQTD ENAME AND SALARY FOR THE EMPLOYEES WHOSE DEPTNO IS 20 ?
SELECT ENAME, SAL
FROM EMP
WHERE DEPTNO = 20;

--43) WAQTD JOB AND DEPTNO OF AN EMPLOYEES WHO ARE  WORKING AS MANAGER ?
SELECT JOB, DEPTNO
FROM EMP
WHERE JOB ='MANAGER';

--44) WAQTD ALL THE DETAILS OF ALL THE EMPLOYEES WHOSE NAME IS KING ?
SELECT *
FROM EMP
WHERE ENAME = 'KING';

--45) WAQTD NAME AND HIREDATE OF ALL THE EMPLOYEES WHO HIRED ON ‘01-JAN-81 ?
SELECT ENAME , HIREDATE
FROM EMP
WHERE HIREDATE = '01-JAN-81';

--46) WAQTD HIREDATE AND DEPTNO OF AN EMPLOYEES WHO HIRED AFTER THE 1981 ?
SELECT HIREDATE , DEPTNO
FROM EMP
WHERE HIREDATE > '31-DEC-1981';

USE EMP;

--47) WAQTD ALL THE DETAILS OF AN EMPLOYEES WHO HIRED BEFORE THE 1987 ?
SELECT *
FROM EMP
WHERE HIREDATE < '31-DEC-1987';

--48) WAQTD ALL THE DETAILS ALONG WITH ANNUAL SALARY FOR ALL THE EMPLOYEES WHOSE SAL IS LESS THEN 5000 ?
SELECT EMP.* ,SAL*12 "ANNUAL SALARY"
FROM EMP
WHERE SAL <5000;;

--49) WAQTD ALL THE DETAILS OF AN EMPLOYEES WHOSE  JOB IS MANAGER ?
SELECT *
FROM EMP
WHERE JOB = 'MANAGER';

--50) WAQTD ENAME AND JOB AND DEPTNO OF ALL THE EMPLOYEES WHO ARE WORKING IN DEPTNO 30 ?
SELECT ENAME , JOB, DEPTNO
FROM EMP
WHERE DEPTNO = 30;

--51) WAQTD ALL THE DETAILS OF AN EMPLOYEES WHOSE JOB IS NOT SALESMAN ?
SELECT *
FROM EMP
WHERE JOB = 'SALESMAN';

--52) WAQTD ENAME AND JOB OF ALL THE EMPLOYEES EXCEPT THE EMPLOYEES OF DEPTNO 20 ?
SELECT ENAME, JOB
FROM EMP
WHERE DEPTNO 10 AND DEPTNO=30;

--53) WAQTD JOB EPTNO AND SAL OF AN ALL THE EMPLOYEES EXCEPT THE EMPLOYEES WHO ARE WORKING AS SALESMAN ?
SELECT JOB, DEPTNO, SAL
FROM EMP
WHERE JOB != 'SALESMAN';

--54) WAQTD DESIGNATION OF ALL THE EMPLOYEES EXCEPT KING ?
SELECT JOB 
FROM EMP
WHERE ENAME <> 'KING';

--55) WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG WITH THAT 20% HIKE OF IN THEIR SALARY FOR THE EMPLOYEES WHO HIRED AFTER 85 ?
SELECT EMP.* , SAL+SAL*20/100 "HIKE IN SAL"
FROM EMP
WHERE HIREDATE > '31-DEC-1985';

--56) WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG WITH THAT 12% DEDUCTION  OF IN THEIR SALARY FOR THE EMPLOYEES WHO HIREDBEFORE 84 ?
SELECT EMP.* SAL-SAL*12/100 "DEDUCTION IN SAL"
FROM EMP
WHERE HIREDATE < '01-JAN-84';

--57) WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG WITH THAT 2000 BONUS  OF IN THEIR SALARY FOR THE EMPLOYEES WHOSE EMPNO IS 7369 ?
SELECT EMP.*, 2000 AS BONOUS
FROM EMP
WHERE EMPNO= 7369;

--58) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHO ARE NOT WORKING IN  DEPTNO 10 ?
SELECT *
FROM EMP
WHERE DEPTNO <> 10;

--59) WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG WITH HALFTERM SALARY FOR ALL THE EMPLOYEE WHOSE ANNUAL SALARY IS MORE THEN 14000 ?
SELECT EMP.*, SAL*6 AS HALF_SAL , SAL*12 AS ANNUAL_SAL
FROM EMP
WHERE SAL > 14000;

--60) WAQTD ALL THE DETAILS OF THE EMPLOYEES ALONG WITH THAT 20% HIKE OF IN THEIR  HALF TERM SALARY FOR ALL THE EMPLOYEES WHOSE HALF TERM SALARY IS MORE THAN 7000 ?
SELECT EMP.*, (SAL+SAL*20/100)/6 "HIKE IN ANNUAL SAL"
FROM EMP
WHERE SAL*6 > 7000;

-->>>>>>>>>>> ASSIGNMENT ON LOGICAL OPERATOR >>>>>>>>>>

--61) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHO ARE WORKING IN DEPTNO 10 AND 20?
SELECT *
FROM  EMP
WHERE DEPTNO = 20 OR DEPTNO = 20;

--62) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHO ARE WORKING AS MANAGER AND SALESMAN ?
SELECT *
FROM EMP
WHERE JOB = 'MANAGER' OR JOB = 'SALESMAN';

--63) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE SAL IS MORE THEN 1000 AND LESS THEN 5000 ?
SELECT *
FROM EMP
WHERE SAL >1000 AND SAL <5000;

--64) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE DEPTNO IS 20 AND WORKING AS MANAGER ?
SELECT *
FROM EMP
WHERE DEPTNO = 20 AND JOB = 'MANAGER';

--65) WAQTD ALL THE EMPLOYEE NAME AND SALARY WHO HIRED AFTER 81 INTO DEPTNO 10 ?
SELECT ENAME , SAL
FROM EMP
WHERE HIREDATE > '31-DEC-81' AND DEPNO = 10;

--66) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE NAME IS KING AND SCOTT ?
SELECT *
FROM EMP
WHERE ENAME = 'KING' AND ENAME = 'SCOTT';

--67) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE SAL IS 3000 AND 5000 ?
SELECT *
FROM EMP
WHERE SAL = 3000 OR SAL = 5000;

--68) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHO ARE WORKING IN DEPTNO 10 AS MANAGER AND HIRED ON ‘17-DEC-82 ?
SELECT *
FROM EMP
WHERE DEPTNO = 10 AND JOB = 'MANAGER' AND HIREDATE = '17-DEC-82';

--69) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHO ARE WORKING AS PRESIDENT IN DEPTNO 10 AND HAVING SALARY OF 5000 ?
SELECT *
FROM EMP
WHERE JOB = 'PRECIDENT' AND DEPTNO = 10 AND SAL = 5000;

--70) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WORKING IN DEPTNO 10,20 AS MANAGER ?
SELECT *
FROM EMP
WHERE (DEPTNO = 10 OR DEPTNO = 20) AND JOB = 'MANAGER';

--71) WAQTD ALL THE EMPLOYEES NAME AND JOB FOR  THE EMPLOYEES WHO HIRED AFTER 81 AND BEFORE 87 ?
SELECT ENAME , JOB 
FROM EMP
WHERE HIREDATE > '31-DEC-81' AND HIREDATE < '01-JAN-87';

--72) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE SALARY ARE MORE THEN 1000 AND LESS THEN 5000 IN DEPTNO 20 ?
SELECT *
FROM EMP
WHERE SAL > 1000 AND SAL < 5000 AND DEPTNO = 20;

--73) WAQTD ALL THE DETAILS OF THE OF THE EMPLOYEES WHO ARE WORKING AS MANAGER IN DEPTNO 20 AND 10AND EARNING COMMISIONS 400,1600 ?
SELECT *
FROM EMP
WHERE JOB = 'MANAGER' AND (DEPTNO = 20 OR DEPTNO = 10) AND (COMM = 400 OR COMM = 1600);

--74) WAQTD ENAME AND ANNAUL SALARY WITH ALISAS NAME FOR THE EMPLOYEES WHOSE ANNUAL SALARY IS MORE THEN 800 IN DEPTNO 30 WORKING   AS SALESMAN AND HIRED BEFORE THE 88 ?
SELECT ENAME, SAL*12 "ANNUAL SALARY" 
FROM EMP
WHERE SAL*12 > 800 AND DEPTNO = 800 AND JOB = 'SALESMAN' AND HIREDATE < '01-JAN-88';

--75) WAQTD ENAME AS A DEPTNO AS B AND JOB AS C FOR THE EMPLOYEES WHOSE COMM IS MORE THE 100 IN DEPTNO 10,20,30 ?
SELECT ENAME AS A, DEPTNO AS B, JOB AS C
FROM EMP
WHERE COMM > 100 AND ( DEPTNO = 10 OR DEPTNO = 20 OR DEPTNO = 30);

--76) WAQTD ALL THE DETAILS FOR THE EMPLOYEEES WHOSE HIREDATE ARE ‘03-DEC-81’ AND ‘17DEC-81’ INTO DEPTNO 30 ?
SELECT *
FROM EMP
WHERE HIREDATE = '03-DEC-81' AND DEPTNO = 30;

--77) WAQTD JOB AND SALARY FOR THE EMPLOYEES WHOSE COMM IS LESS THEN 2000 AND SALARIES ARE MORE THEN 1000 IN DEPTNO 10, 20?
SELECT JOB, SAL
FROM EMP
WHERE COMM <2000 AND SAL > 1000 AND ( DEPTNO = 10 OR DEPTNO =20);

--78) WAQTD ALL THE DEATILS  FOR THE EMPLOYEES WHOSE NAMES ARE KING AND SMITH AND ALLEN ?
SELECT *
FROM EMP
WHERE ENAME = 'KING' OR ENAME = 'SMITH' OR ENAME = 'ALLEN';

--79) WAQTD ANNUAL SALARY HALF TERM SALARY WITH 25% DEDUCTION IN THE SALARY FOR THE EMPLOYEES WHOSE ANNUAL SALARY IS MORE THEN 6000 ?
SELECT SAL*12 "ANNUAL SAL", SAL*6 "HALF TERM SAL" , SAL+SAL*25/100
FROM EMP
WHERE SAL*12 > 6000;

--80) ALL THE DETAILS AND HALF TERM SALARY FOR SALESMAN AND MANAGER IN DEPTNO 10,30 ?
SELECT EMP.* , SAL*6 "HALF TERM SAL"
FROM EMP
WHERE JOB = ('SALESMAN' OR JOB = 'MANAGER') AND (DEPTNO = 10 OR DEPTNO =30);


-->>>>>>>>>>> ASSIGNMENT ON SPECIAL OPERATOR >>>>>>>>>>>
--81) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHO ARE WORKING IN DEPTNO 10 AND 20?
SELECT *
FROM EMP
WHERE DEPTNO IN(10,20);

--82) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHO ARE WORKING AS MANAGER AND SALESMAN ?
SELECT *
FROM EMP
WHERE JOB IN ('MANAGER', 'SALESMAN');

--83) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE SAL IS MORE THEN 1000 AND LESS THEN 5000 ?
SELECT *
FROM EMP
WHERE SAL > 1000 AND SAL < 5000;

--84) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE DEPTNO IS 20 AND WORKING AS MANAGER ?
SELECT *
FROM EMP
WHERE DEPTNO = 20 AND JOB IN ('MANAGER' , 'SALESMAN');

--85) WAQTD ALL THE EMPLOYEE NAME AND SALARY WHO HIRED AFTER 81 INTO DEPTNO 10 ?
SELECT ENAME , SAL
FROM EMP
WHERE HIREDATE > '01-JAN-81' AND DEPTNO = 10;

--86) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE NAME IS KING AND SCOTT ?
SELECT *
FROM EMP
WHERE ENAME IN('KING' , 'SCOTT');

--87) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE SAL IS 3000 AND 5000 ?
SELECT *
FROM EMP
WHERE SAL IN(3000 , 5000);

--88) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHO ARE WORKING IN DEPTNO 10 AS MANAGER AND HIRED ON ‘17-DEC-82 ?
SELECT *
FROM EMP
WHERE DEPTNO = 10 AND JOB = ' MANAGER ' AND HIREDATE = '17-NOV-82' ;

--89) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHO ARE WORKING AS PRESIDENT IN DEPTNO 10 AND HAVING SALARY OF 5000 ?
SELECT *
FROM EMP
WHERE JOB = 'PRESIDENT' AND DEPTNO = 10 AND SAL= 5000;

--90) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WORKING IN DEPTNO 10,20 AS MANAGER ?
SELECT *
FROM EMP
WHERE DEPTNO IN(10,20) AND JOB = 'MANAGER';

--91) WAQTD ALL THE EMPLOYEES NAME AND JOB FRO THE EMPLOYEES WHO HIRED AFTER 81 AND BEFORE 87 ?
SELECT  ENAME , JOB 
FROM EMP
WHERE HIREDATE > '31-DEC-81' AND HIREDATE < '31-DEC-87';

--92) WAQTD ALL THE DETAILS OF THE EMPLOYEES  WHOSE SALARY ARE MORE THEN 1000 AND LESS THEN 5000 IN DEPTNO 20 ?
SELECT *
FROM EMP
WHERE SAL > 1000 AND SAL <5000 AND DEPTNO = 20;

--93) WAQTD ALL THE DETAILS OF THE OF THE EMPLOYEES WHO ARE WORKING AS MANAGER IN DEPTNO 20 AND 10 AND EARNING COMMISIONS 400,1600 ?
SELECT *
FROM EMP
WHERE JOB = 'MANAGER' AND DEPTNO IN(10,20) AND COMM IN(400,600);

--94) WAQTD ENAME AND ANNAUL SALARY WITH ALISAS NAME FOR THE EMPLOYEES WHOSE ANNUAL SALARY IS MORE THEN 800 IN DEPTNO 30 WORKING AS SALESMAN AND HIRED BEFORE THE 88 ?
SELECT ENAME , SAL * 12 AS "ANNUAL SALARY"
FROM EMP
WHERE SAL*12 > 800 AND DEPTNO =30 AND JOB = 'SALESMAN' AND HIREDATE < '01-JAN-88';

--95) WAQTD ENAME AS A DEPTNO AS B AND JOB AS C FOR THE EMPLOYEES WHOSE COMM IS MORE THE 100 IN DEPTNO 10,20,30 ?
SELECT ENAME AS A , DEPTNO AS B , JOB AS C, 
FROM EMP
WHERE COMM > 100 OR DEPTNO IN (10,20,30);

--96) WAQTD ALL THE DETAILS FOR THE EMPLOYEEES WHOSE HIREDATE ARE ‘03-DEC-81’ AND ‘17DEC-81’ INTO DEPTNO 30 ?
SELECT *
FROM EMP
WHERE HIREDATE IN('03-DEC-81' , '17-DEC-81') AND DEPTNO =30;

--97) WAQTD JOB AND SALARY FOR THE EMPLOYEES WHOSE COMM IS LESS THEN 2000 AND SALARIES ARE MORE THEN 1000 IN DEPTNO 10, 20?
SELECT JOB , SAL
FROM EMP
WHERE COMM < 2000 AND SAL > 1000 AND DEPTNO IN(10,20);

--98) WAQTD ENAME FOR THE EMPLOYEES WHOSE NAMES ARE KING AND SMITH AND ALLEN ?
SELECT ENAME 
FROM EMP
WHERE ENAME IN ('SMITH' , 'ALLEN');

--99) WAQTD ANNUAL SALARY HALF TERM SALARY WITH 25% DEDUCTION IN THE SALARY FOR THE EMPLOYEES WHOSE ANNUAL SALARY IS MORE THEN 6000 ?
SELECT SAL*12 "ANNUAL SAL" , (SAL-SAL*25/100)12 " DEDUCTION IN SAL"
FROM EMP
WHERE SAL*12 > 6000;

--100) ALL THE DETAILS AND HALF TERM SALARY FOR SALESMAN AND MANAGER IN DEPTNO 10,30 ?
SELECT EMP.*, SAL*6 AS HALF_SAL
FROM EMP
WHERE JOB IN ('SALESMAN' , ' MANAGER' ) AND DEPTNO IN(10,30);

--101) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHOSE HIRED BETWEEN 81 TO 89  INTO DEPTNO 20 ?
SELECT *
FROM EMP
WHERE HIREDATE BETWEEN 81 AND 89 AND DEPTNO = 20;

--102) WAQTD DETAILS FOR THE EMPLOYEES WHOSE SALARY IN THE RANGE OF 1000 TO 5000 IN DEPTNO 10,20 ?
SELECT *
FROM EMP
WHERE SAL BETWEEN 1000 AND 5000 AND DEPTNO IN(10, 20);


--103) WAQTD ENAME AND JOB FOR THE EMPLOYEES WHO ARE WORKING AS ANAGER AND EARNING COMMISION IN THE RANGE OF 100 TO 1000 ?
SELECT ENAME , JOB
FROM EMP
WHERE JOB = 'MANAGER' AND COMM BETWEEN 100 AND 1000;

--104) WAQTD ALL THE DEATILS ALONG WITH 3 MONTHS SALARY FOR THE EMPLOYEES WHOSE SALARY IS NOT NULL AND DOESNT HAVING ANY REPORTING MANAGER  ?
SELECT EMP.* , SAL*3 "3_MONTH SAL"
FROM EMP
WHERE SAL IS NOT NULL AND MGR IS NULL;

--105) WAQTD ENAME AND SALARY AND JOB FOR THE EMPLOYEES WORKING AS SALESMAN IN DEPTNO 30 AND EARNING SALARY BUT NOT COMMISION AND HIRED BETWEEN 82  TO 88 ? 
SELECT ENAME , SAL , JOB
FROM EMP
WHERE JOB = 'SALESMAN' AND DEPTNO = 30 AND SAL IS NOT NULL AND COMM IS NULL AND HIREDATE BETWEEN 82 AND 88;

--106) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHO ARE EARNING SALARY ?
SELECT *
FROM EMP
WHERE SAL IS NOT NULL;

--107) WAQTD ANNAUL SALARY OF THE EMPLOYEE WHO ARE NOT EARNING COMMISSION ?
SELECT EMP.* , SAL*12 AS ANNUAL_SAL
FROM EMP 
WHERE COMM IS NULL;

--108) WAQTD ALL THE DETAILS WITH ANNAUL COMMISSION FOR THE EMPLOYEE WHO  ARE WORKING IN DEPT 10 AND DONT HAVE ANY REPORTING MANAGER ?
SELECT EMP.* , COMM*12 "ANNUAL COMMISSION"
FROM EMP
WHERE DEPTNO =10 AND MGR = NULL;

--109) WAQTD ALL THE DETAILS OF THE EMPLOYEE EXCEPT DEPTNO 10 AND WHO WHO HAVE REPORTING MAMAGER ?
SELECT *
FROM EMP
WHERE DEPTNO NOT IN (10) AND MGR IS NOT NULL;

--110) WAQTD ENAME AND SALARY. AND COMMISSION OF THE EMPLOYEE WHO EARNING COMMISSION IN DEPT NO 30 AND WORKING AS SALESMAN ?
SELECT ENAME, SAL , COMM
FROM EMP
WHERE COMM IS NOT NULL AND DEPTNO = 30 AND JOB = 'SALESMAN';

--111) WAQTD ENAME OF THE EMPLOYEE WHOSE NAME START WITH S 
SELECT ENAME
FROM EMP
WHERE ENAME LIKE 'S%';

--112 ) WAQTD ALL THE DETAILS FOR THE EMPLOYEE WHOSE NAME ENDS WITH R ?
SELECT *
FROM EMP
WHERE ENAME LIKE '%E';

--113 ) WAQTD SALARY AND DEEPTNO AND NAME FOR THE EMPLOYEE WHOSE NAME HAVING A CHARACTER ?
SELECT SAL, DEPTNO, ENAME
FROM EMP
WHERE ENAME LIKE ' %A%';

--114 ) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE HAVING 2 A IN THEIR NAME ?
SELECT *
FROM EMP
WHERE ENAME LIKE '%A%A%';

--115 ) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME HAVING CONJUGATIVE A IN THEIR NAMES ?
SELECT *
FROM EMP 
WHERE ENAME LIKE '%AA%';

--116) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME HAVING  2ND CHARACTER AS M ?
SELECT *
FROM EMP
WHERE ENAME LIKE '_M%';

--117) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME HAVING LAST 2ND CHAPTER AS E ?
SELECT *
FROM EMP
WHERE ENAME LIKE '%E_';

--118) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME START WITH M HAVING 4TH CHARACTER L AND ENDS WITH R ?
SELECT *
FROM EMP
WHERE ENAME LIKE 'M__L%';

--119) WAQTD ALL THE DETAILS OF AN ALL THE EMPLOYEE WHO ARE EARNING 4 DOGIT OF SALARY AND NAMES STARTS WITH VOWELS ?
SELECT *
FROM EMP
WHERE SAL LIKE '____' AND REGEXP_LIKE(ENAME,'^[A,E,I,O,U]');

--120 ) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME STARTS WITH CONSONANTS. ?
SELECT *
FROM EMP
WHERE NOT REGEXP_LIKE(ENAME, '^[A,E,I,O,U]'); 

--121) WAQTD ENAME AND HIREDATE OF ALL THE EMPLOYEE WHO HIRED IN THE MONTH OF DEC ?
SELECT ENAME , HIREDATE 
FROM EMP
WHERE HIREDATE LIKE '%DEC%';

--122) WAQTD ALL THE DETAILS FOR THE EMPLOYEE WHO HIRED DURING 1981 ?
SELECT *
FROM EMP
WHERE HIREDATE LIKE '%1981';

--123) WAQTD ALL THE DETAILS OF THE EMPLOYEE EXCEPT WHOSE NAME HAVING A ?
SELECT *
FROM EMP
WHERE ENAME NOT LIKE '%A%';

--124) WAQTD SALARY AND NAMES FOR THE EMPLOYEE WHOSE NAME START WITH S EXCEPT THE EMPLOYEE SALARY. STARTS WITH 1 ?
SELECT SAL, ENAME
FROM EMP
WHERE ENAME LIKE 'S%' AND SAL NOT LIKE '1%';

--125) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME HAVING 2 TIME CONSUGATIVE. A ?
SELECT *
FROM EMP
WHERE ENAME LIKE '%AA%';

--126) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME START WITH % ?
SELECT *
FROM EMP
WHERE REGEXP LIKE(ENAME , '^%');

--127) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME ENDS WITH % ?
SELECT *
FROM EMP
WHERE REGEXP LIKE(ENAME , '%$');

--128) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME START WITH % ENDS WITH _ ?
SELECT *
FROM EMP
WHERE REGEXP LIKE(ENAME , '^%$_');

--129) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME HAVING % ?
SELECT *
FROM EMP
WHERE REGEXP LIKE(ENAME , '.*%.*');

--130) WAQTD ALL THE DETAILS OF THE EMPLOYEE WHOSE NAME START WITH % HAVING 4TH CHARACTER _ AND ENDS WITH % ?
SELECT *
FROM EMP
WHERE REGEXP LIKE(ENAME , '^%.._$%');

>>>>>>>>>>>>>>ASSINGMENT ON MRF >>>>>>>>>>>>>>>>>>

--131) WAQTD MAX SALARY FROM THE EMPLOYEE TABLE ?
SELECT MAX(SAL)
FROM EMP;

--132) WAQTD MAX AND MIN COMM FROM EMPLOYEES TABLE ?
SELECT MAX(COMM), MIN(COMM)
FROM EMP;

--133) WAQTD TOTAL SALARY NEEDED TO PAY FOR THE SALESMAN ?
SELECT SUM(SAL)
FROM EMP
WHERE JOB = 'SALESMAN';

--134) WAQTD NUMBER OF EMPLOYEES WORKING IN DEPTNO 30 ?
SELECT COUNT(*)
FROM EMP
WHERE DEPTNO = 30;

--135) WAQTD NUMBER OF EMPLOYEES WORKING AS MANAGER IN DEPTNO 20?
SELECT COUNT(*)
FROM EMP
WHERE JOB = 'MANAGER' AND DEPTNO = 10;

--136) WAQTD MAX SALARY NEEDED TO PAY FOR THE EMPLOYEES WHOSE NAME STARTS WITH A ?
SELECT MAX(SAL) 
FROM EMP
WHERE ENAME LIKE 'A%';

--137) WAQTD AVG SALARY NEEDED TO PAY FOR THE EMPLOYEES OF DEPTNO 10 ?
SELECT AVG(SAL)
FROM EMP
WHERE DEPTNO = 10;

--138) WAQTD TOTAL SALARY AND AVG SALARY NEEDED TO PAY FOR THE EMPLOYEES WHO ARE HIRED IN THE RANGE OF 81 TO 87 ?
SELECT COUNT(*)
FROM EMP
WHERE HIREDATE BETWEEN ('01-JAN-81'AND'31-DEC-87');

--139) WAQTD NUMBER OF EMPLOYEES WORKING IN DEPTNO 30 ?
SELECT COUNT(*)
FROM EMP
WHERE DEPTNO = 30;


--140) WAQTD TOTAL SALARY NEEDED TO PAY FOR THE EMPLOYEES WHO ARE REPORTING TO 7839 ?
SELECT SUM(SAL)
FROM EMP
WHERE MGR = 7839;

--141) WAQTD HOW MANY EMPLOYEES ARE WORKIN AS PRESIDENT IN DEPTNO 10 AND EARNING SALARY MORE THEN 4000 ?
SELECT COUNT(*)
FROM EMP
WHERE JOB = 'PRESIDENT' AND DEPTNO = 10 AND SAL > 4000;

--142) WAQTD HOW MANY EMPLOYEES ARE WORKIN AS SALESMAN IN DEPTNO 30 AND EARNING SALARY LESS THEN 5000 ?
SELECT COUNT(*)
FROM EMP
WHERE JOB = 'SALESMAN' AND DEPTNO = 30 AND SAL < 5000;

--143) WAQTD HOW MANAY EMPLOYEES ARE HIRED ON 03-DEC- 81 iN DEPTNO 10 , 20
SELECT COUNT(*)
FROM EMP
WHERE HIREDATE = '03-DEC-81' AND DEPTNO IN (10, 20);

--144) WAQTD HOW MUCH TOTAL SALARY NEEDE TO PAY FOR THE EMPLOYEE WHOSE MAME HAVING A CHARACTER ?
SELECT SUM(SAL)
FROM EMP
WHERE ENAME LIKE '%A%';

--145) WAQTD AVG SALARY NEEDED TO PAY FOR THE SALESMAN IN DEPTNO 30 ?
SELECT AVG(SAL)
FROM EMP
WHERE JOB = 'SALESMAN' AND DEPT = 30;


-->>>>>>>>> ASSIGNMENT ON GROUP BY CLAUSE >>>>>>>>>>>>>

--146).WAQTD NUMBER OF EMPLOYEES WORKING IN EACH DEPARTEMENT EXCEPT PRESIDENT. ?
SELECT COUNT(*) AS COUNT_EMP
FROM EMP
WHERE JOB != 'PRESIDENT'
GROUP BY DEPTNO;

--147)WAQTD TOTAL SALARY NEEDED TO PAY ALL THE EMPLOYEES IN EACH JOB. ?
SELECT SUM(SAL) AS SUM_OF_SAL_IN_JOB
FROM EMP
GROUP BY JOB;

--148)WAQTD NUMBER OF EMPLOYEEES WORKING AS MANAGER IN EACH DEPARTMENT. ?
SELECT COUNT(*) AS MANAGER 
FROM EMP
WHERE JOB = 'MANAGER'
GROUP BY DEPTNO;


--149).WAQTD AVG SALARY NEEDED TO PAY ALL THE EMPLOYEES IN EACH DEPARTMENT EXCLUDING THE EMPLOYEES OF DEPTNO 20 . ? 
SELECT AVG(SAL) 
FROM EMP
WHERE DEPTNO != 20
GROUP BY DEPTNO;

--150).WAQTD NUMBER OF EMPLOYEES HAVING CHARACTER 'A' IN THEIR NAMES IN EACH JOB.  ?
SELECT COUNt(*)
FROM EMP
WHERE ENAME LIKE '%A%'
GROUP BY JOB;

--151).WAQTD NUMBER OF EMPLOYEES AND AVG SALARY NEEDED TO PAY THE EMPLOYEES WHO SALARY IN GREATER THAN 2000 IN EACH DEPT. ?
SELECT COUNT(*) AVG(SAL)
FROM EMP
WHERE SAL > 2000 
GROUP BY DEPTNO;

--152)WAQT D TOTAL SALARY NEEDED TO PAY AND NUMBER OF SALESMANS IN EACH DEPT. ?
SELECT SUM(SAL) 
FROM EMP
WHERE JOB = 'SALESMAN' 
GROUP BY DEPTNO;

--153)WAQTD NUMBER OF EMPLOYEES WITH THEIR MAXIMUM SALARIES IN EACH JOB. ?
SELECT COUNT(*) , MAX(SAL)
FROM EMP
GROUP BY JOB;

--154) WAQTD MAXIMUM SALARIES GIVEN TO AN EMPLOYEE WORKING IN EACH DEPT. ?
SELECT MAX(SAL) MAX_SAL_IN_EACH_DEPT
FROM EMP
GROUP BY DEPTNO;

--155)WAQTD NUMBER OF TIMES THE SALARIES PRESENT IN EMPLOYEE TABLE. ?
SELECT COUNT(SAL)
FROM EMP;


--<<<<<<<<<<<ASSIGNMENT QUESTIONS ON HAVING CLAUSE>>>>>>>>>>>>

--156).WAQTD DNO AND NUMBER OF EMP WORKING IN EACH DEPT IF THERE ARE ATLEAST 2 CLERKS IN EACH DEPT ?
SELECT DEPTNO , COUNT(*)
FROM EMP


--157)WAQTD DNO AND TOTAL SAALARY NEEDED TO PAY ALL EMP IN EACH DEPT IF THERE ARE ATLEAST 4 EMP IN EACH DEPT ?
SELECT SUM(SAL)
FROM EMP
GROUP BY DEPTNO
HAVING COUNT(SAL) >= 4;

USE EMP;

--158).WAQTD NUMBER OF EMP EARNING SAL MORE THAN 1200 IN EACH JOB AND THE TOTAL SAL NEEDED TO PAY EMP OF EACH JOB MUST EXCEEDS 3800 ?
SELECT COUNT(EMP)
FROM EMP
WHERE SAL > 1200 
GROUP BY JOB
HAVING SUM(SAL) > 3000;

--159).WAQTD DEPTNO AND NUMBER OF EMP WORKING ONLY IF THERE ARE 2 EMP WORKING IN EACH DEPT AS MANAGER. ?


--160) WAQTD JOB AND MAX SAL OF EMP IN EACH JOB IF THE MAX SAL EXCEEDS 2600 ?
SELECT JOB , MAX(SAL) 
FROM EMP
HAVING MAX(SAL) > 2600;

--161). WAQTD THE SALARIES WHICH ARE REPEATED IN EMP TABLE ?
SELECT SAL
FROM EMP
GROUP BY SAL
HAVING COUNT(SAL) > 1;


--162).WAQTD THE HIREDATE WHICH ARE DUPLICATED IN EMP TABLE ?
SELECT HIREDATE 
FROM EMP
GROUP BY HIREDATE
HAVING COUNT(HIREDATE) > 1;


--164) WAQTD AVG SALARY OF EACH DEPT IF AVG SAL IS LESS THAN 3000 ?
SELECT AVG(SAL)
FROM EMP
HAVING AVG(SAL) < 3000;

--164) WAQTD DEPTNO IF THERE ARE ATLEAST 3 EMP IN EACH DEPT WHOS NAME HAS CHAR 'A' OR 'S' ?
SELECT DEPTNO 
FROM EMP
WHERE ENAME LIKE '%A%S%'
HAVING COUNT(*) = 3;
GROUP BY DEPTNO;

--165).WAQTD MIN AND MAX SALARIES OF EACH JOB IF MIN SAL IS MORE THAN 1000 AND MAX SAL IS LESS THAN 5000.
SELECT MIN(SAL) , MAX(SAL) 
FROM EMP
HAVING MIN(SAL) > 100 AND MAX(SAL) <5000;


--<<<<<<<<<ASSIGNMENT ON SUB QUERIES>>>> >>>>
--ASSIGNMENT ON CASE 1

--166).WAQTD NAME OF THE EMPLOYEES EARNING MORE THAN ADAMS ?
SELECT ENAME
FROM EMP
WHERE SAL > (SELECT SAL
			FROM EMP
			WHERE ENAME = 'ADAMS');


--167).WAQTD NAME AND SALARY OF THE EMPLOYEES EARNING LESS THAN KING
SELECT ENAME , SAL 
FROM EMP
WHERE SAL < ( SELECT SAL
			FROM EMP
			WHERE ENAME = 'KING');

			SELECT * FROM EMP;

--168) WAQTD NAME AND DEPTNO OF THE EMPLOYEES IF THEY ARE WORKING IN THE SAME DEPT AS JONES
SELECT ENAME , DEPTNO
FROM EMP
WHERE DEPTNO = ( SELECT DEPTNO
				FROM EMP
				WHERE ENAME = 'JONES');


--169) WAQTD NAME AND JOB OF ALL THE EMPLOYEES WORKING IN THE SAME DESIGNATION AS JAMES 
SELECT ENAME , JOB
FROM EMP
WHERE JOB = ( SELECT JOB 
			FROM EMP
			WHERE ENAME = 'JAMES');


--170)WAQTD EMPNO AND ENAME ALONG WITH ANNUAL SALARY OF ALL THE EMPLOYEES IF THEIR ANNUAL SALARY IS GREATER THAN WARDS ANNUAL SALARY.
SELECT EMPNO , ENAME, SAL*12 AS A_SAL
FROM EMP
WHERE SAL*12 > (SELECT SAL*12
				FROM EMP
				WHERE ENAME = 'WARDS');

--171) .WAQTD NAME AND HIREDATE OF THE EMPLOYEES IF THEY ARE HIRED BEFORE SCOTT AND HIRED AFTER THE PRESIDENT ?
SELECT HIREDATE
FROM EMP
WHERE HIREDATE > (SELECT HIREDATE
				 FROM EMP
				 WHERE ENAME = 'SCOTT') AND HIREDATE  < (SELECT HIREDATE
														FROM EMP
														WHERE ENAME = 'PRESIDENT');



--172) .WAQTD NAME AND SAL OF THE EMPLOYEE IF THEY ARE EARNING SAL LESS THAN THE EMPLOYEE WHOS EMPNO IS 7839
SELECT ENAME , SAL 
FROM EMP
WHERE SAL < (SELECT SAL
			FROM EMP
			WHERE EMPNO = 7839);


173).WAQTD ALL THE DETAILS OF THE EMPLOYEES IF THE EMPLOYEES ARE HIRED BEFORE MILLER 
--DOUGHT
SELECT *
FROM EMP
WHERE HIREDATE < (SELECT HIREDATE
				FROM EMP
				WHERE ENAME = 'MILLER');


--174) .WAQTD ENAME AND EMPNO OF THE EMPLOYEES IF EMPLOYEES ARE EARNING MORE THAN ALLEN
SELECT ENAME , EMPNO
FROM EMP
WHERE SAL > (SELECT SAL
			FROM EMP
			WHERE ENAME = 'ALLEN');

--175).WAQTD ENAME AND SALARY OF ALL THE EMPLOYEES WHO ARE EARNING MORE THAN MILLER BUT LESS THAN ALLEN.
SELECT ENAME, SAL
FROM EMP
WHERE SAL > (SELECT SAL 
			FROM EMP
			WHERE ENAME = 'MILLER') AND SAL  < (SELECT SAL
												FROM EMP
												WHERE ENAME = 'ALLEN');

--178).WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING IN DEPT 20 AND WORKING IN THE SAME DESIGNATION AS SMITH 
SELECT *
FROM EMP
WHERE DEPTNO = 20 AND JOB = (SELECT JOB
							FROM EMP
							WHERE ENAME = 'SMITH');

--179).WAQTD ALL THE DETAILS OF THE EMPLOYEES WORKING AS MANAGER IN THE SAME DEPT AS TURNER
SELECT *
FROM EMP
WHERE JOB = 'MANAGER' AND DEPTNO = (SELECT DEPTNO
									FROM EMP
									WHERE ENAME = 'TURNER');

--180).WAQTD NAME AND HIREDATE OF THE EMPLOYEES HIRED AFTER 1980 AND BEFORE KING 
SELECT ENAME , HIREDATE
FROM EMP
WHERE HIREDATE > '01-JAN-1980' AND HIREDATE < (SELECT HIREDATE
												FROM EMP
												WHERE ENAME = 'KING');

--181).WAQTD ALL THE DETAILS OF EMPLOYEES WHO EARN MORE THAN SCOTT BUT LESS THAN KING
SELECT *
FROM EMP
WHERE SAL > (SELECT SAL
			FROM EMP
			WHERE ENAME = 'SCOTT') AND SAL < (SELECT SAL
											  FROM EMP
											  WHERE ENAME = 'KING');

--182).WAQTD NAME OF THE EMPLOYEES WHOS NAME STARTS WITH 'A' AND WORKS IN THE SAME DEPT AS BLAKE 
SELECT ENAME
FROM EMP
WHERE ENAME LIKE 'A%' AND DEPTNO = (SELECT DEPTNO
									FROM EMP 
									WHERE ENAME = 'BLAKE');

--183).WAQTD NAME AND COMM IF EMPLOYEES EARN COMMISSION AND WORK IN THE SAME DESIGNATION AS SMITH
SELECT ENAME, COMM
FROM EMP
WHERE COMM IS NOT NULL AND JOB = (SELECT JOB
								 FROM EMP
								 WHERE ENAME = 'SMITH');


--184).WAQTD DETAILS OF ALL THE EMPLOYEES WORKING AS CLERK IN THE SAME DEPT AS TURNER.
SELECT *
FROM EMP
WHERE JOB = 'CLERK' AND DEPTNO = (SELECT DEPTNO
								 FROM EMP
								 WHERE ENAME = 'TURNER');


--185).WAQTD ENAME, SAL AND DESIGNATION OF THE EMPLOYEES WHOS ANNUAL SALARY IS MORE THAN SMITH AND LESS THAN KING.
SELECT ENAME , SAL ,JOB
FROM EMP
WHERE SAL*12 > (SELECT SAL*12
				FROM EMP
				WHERE ENAME = 'SMITH') AND SAL*12 < (SELECT SAL*12
													FROM EMP
													WHERE ENAME = 'KING');


--ASSIGNMENT ON CASE 2:

--186).WAQTD DNAME OF THE EMPLOYEES WHOS NAME IS SMITH 
SELECT DNAME
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO
				FROM EMP
				WHERE ENAME = 'SMITH');

--187).WAQTD DNAME AND LOC OF THE EMPLOYEE WHOS ENAME IS KING 
SELECT DNAME , LOC
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO 
				FROM EMP
				WHERE ENAME = 'KING');


--188).WAQTD LOC OF THE EMP WHOS EMPLOYEE NUMBER IS 7902
SELECT LOC
FROM DEPT 
WHERE DEPTNO = ( SELECT DEPTNO
				FROM EMP
				WHERE EMPNO = 7902);

-- 189) WAQTD DNAME AND LOC ALONG WITH DEPTNO OF THE EMPLOYEE WHOS NAME ENDS WITH 'R'.
SELECT DNAME , LOC
FROM DEPT
WHERE DEPTNO =ANY (SELECT DEPTNO
				FROM EMP
				WHERE ENAME LIKE '%R');

--190) .WAQTD DNAME OF THE EMPLOYEE WHOS DESIGNATION IS PRESIDENT
SELECT DNAME
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO
				FROM EMP
				WHERE JOB = 'PRESIDENT');

--191) .WAQTD NAMES OF THE EMPLOYEES WORKING IN ACCOUNTING DEPARTMENT
SELECT ENAME
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
				FROM DEPT
				WHERE DNAME = 'ACCOUNTING');

SELECT * FROM DEPT;

--192) .WAQTD ENAME AND SALARIES OF THE EMPLOYEES WHO ARE WORKING IN THE LOCATION CHICAGO
SELECT ENAME , SAL
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
				FROM DEPT
				WHERE LOC = 'CHICAGO');


--193). WAQTD DETAILS OF THE EMPLOYEES WORKING IN SALES 
SELECT *
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
				FROM DEPT
				WHERE DNAME = 'SALES');

--194) .WAQTD DETAILS OF THE EMP ALONG WITH ANNUAL SALARY IF EMPLOYEES ARE WORKING IN NEW YORK
SELECT EMP.*, SAL*12 AS ASAL
FROM EMP
WHERE DEPTNO =(SELECT DEPTNO 
			   FROM DEPT
			   WHERE LOC = 'NEW YORK');

--195) .WAQTD NAMES OF EMPLOYEES WORKING IN OPERATIONS DEPARTMENT
SELECT ENAME
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO 
				FROM DEPT
				WHERE DNAME = 'OPERATIONS');


--ASSIGNMENT ON CASE 1 & 2

--195) .WAQTD NAMES OF THE EMPLOYEES EARNING MORE THAN SCOTT IN ACCOUNTING DEPT
SELECT ENAME
FROM EMP
WHERE SAL = (SELECT SAL
			FROM DEPT
			WHERE DNAME = 'ACCOUNTING');

--196). WAQTD DETAILS OF THE EMPLOYEES WORKING AS MANAGER IN THE LOCATION CHICAGO 
SELECT *
FROM EMP
WHERE JOB = 'MANAGER' AND DEPTNO IN (SELECT DEPTNO
									FROM DEPT
									WHERE LOC = 'CHICAGO');

--197) .WAQTD NAME AND SAL OF THE EMPLOYEES EARNING MORE THAN KING IN THE DEPT ACCOUNTING
SELECT ENAME, SAL
FROM EMP
WHERE SAL > (SELECT SAL
			FROM EMP
			WHERE ENAME = 'KING')  AND DEPTNO = (SELECT DEPTNO
											   FROM DEPT
											   WHERE DNAME = 'ACCOUNT');
USE EMP;

--198) .WAQTD DETAILS OF THE EMPLOYEES WORKING AS SALESMAN IN THE DEPARTEMENT SALES 
SELECT *
FROM EMP
WHERE JOB = 'SALESMAN' AND DEPTNO = (SELECT DEPTNO
									FROM DEPT
									WHERE DNAME = 'SALES');

--199) .WAQTD NAME, SAL. JOB, HIREDATE OF THE EMPLOYEES WORKING IN OPERATIONS DEPARTMENT AND HIRED BEFORE KING
SELECT ENAME , SAL, JOB , HIREDATE
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
				FROM DEPT
				WHERE DNAME = ' OPERATIONS') AND HIREDATE = (SELECT HIREDATE
															FROM EMP 
															WHERE ENAME = 'KING');
--200) .DISPLAY ALL THE EMPLOYEES WHOSE DEPARTMET NAMES ENDING 'S'.
SELECT *
FROM EMP 
WHERE DEPTNO IN (SELECT DEPTNO
				FROM DEPT
				WHERE DNAME LIKE '%S');

--201) .WAQTD DNAME OF THE EMPLOYEES WHOS NAMES HAS CHARACTER 'A' IN IT.
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO
				FROM EMP
				WHERE ENAME LIKE '%A%');

--202) . WAQTD DNAME AND LOC OF THE EMPLOYEES WHOS SALARY IS RUPEES 800. 
SELECT DNAME , LOC
FROM DEPT
WHERE DEPTNO IN (SELECT SAL
						FROM EMP
						WHERE SAL = 800);


--203) .WAQTD DNAME OF THE EMPLOYEES WHO EARN COMISSION
SELECT DNAME
FROM DEPT 
WHERE DEPTNO IN (SELECT DEPTNO
				FROM EMP
				WHERE COMM IS NOT NULL);

--204) .WAQTD LOC OF THE EMPLOYEES IF THEY EARN COMISSION IN DEPT 40
SELECT LOC
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO
				FROM EMP
				WHERE COMM IS NULL AND DEPTNO = 30);

--ASSIGNMENT ON TYPES OF SUB QUERY.

--205) .WAQTD NAME OF THE EMPLOYEES EARNING SALARY MORE THAN THE SALESMAN
SELECT ENAME 
FROM EMP
WHERE SAL < ANY (SELECT SAL
			FROM EMP
			WHERE JOB = 'SALESMAN');

--206) WAQTD DETAILS OF THE EMPLOYEES HIRED AFTER ALL THE CLERKS
SELECT *
FROM EMP
WHERE HIREDATE >ALL ( SELECT HIREDATE
					FROM EMP
					WHERE JOB = 'CLEARK');

--208) WAQTD NAME AND HIREDATE OF EMPLOYEES HIRED BEFORE ALL THE MANAGERS
SELECT ENAME , HIREDATE
FROM EMP
WHERE HIREDATE <ALL (SELECT HIREDATE
					FROM EMP
					WHERE JOB = 'MANAGER');

--209) .WAQTD NAMES OF THE EMPLOYEES HIRED AFTER ALL THE MANAGERS AND EARNING SALARY MORE THAN ALL THE CLERKS
SELECT ENAME 
FROM EMP
WHERE HIREDATE >ALL (SELECT HIREDATE
					FROM EMP
					WHERE JOB = 'MANAGER') AND SAL >ALL (SELECT SAL
														FROM EMP
														WHERE JOB = 'CLERK');

--210) .WAQTD DETAILS OF THE EMPLOYEES WORKING AS CLERK AND HIRED BEFORE ATLEST A SALESMAN 
SELECT *
FROM EMP
WHERE JOB = 'CLERK' AND HIREDATE <ANY (SELECT HIREDATE
										FROM EMP
										WHERE JOB = 'SALESMAN');

USE DEPT;
--211).WAQTD DETAILS OF EMPLOYEES WORKING IN ACCOUNTING OR SALES DEPT
SELECT *
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
				FROM DEPT
				WHERE DNAME = ACCOUNTING OR DNAME = 'SALES');

--212) WAQTD DEPARTMENT NAMES OF THE EMPOYEES WITH NAME SMITH, KING AND MILLER
SELECT DNAME 
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO
				FROM EMP
				WHERE ENAME IN('SMITH', 'KING' , 'MILLER'));

--213) .WAQTD DETAILS OF EMPLOYEES WORKING NEWYORK OR CHICAGO
SELECT *
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
				FROM DEPT
				WHERE LOC IN( 'NEWYORK' , 'CHICAGO'));

--214)  WAQTD EMP NAMES IF EMPLOYEES ARE HIRED AFTER ALL THE EMPLOYEES OF DEPT 10
SELECT ENAME
FROM EMP
WHERE HIREDATE >ALL (SELECT HIREDATE
				  FROM EMP
				  WHERE DEPTNO = 10);

--ASSIGNMENT ON NESTED SUB QUERY:

--61. WAQTD 2ND MINIMUM SALARY
SELECT MIN(SAL)
FROM EMP
WHERE SAL > (SELECT MIN(SAL)
			FROM EMP);

--62. WAQTD 5TH MAXIMUM SALARY
SELECT MAX(SAL)
FROM EMP
WHERE SAL < (SELECT MAX(SAL)
			 FROM EMP
			 WHERE SAL < (SELECT MAX(SAL)
						  FROM EMP
						  WHERE SAL < (SELECT MAX(SAL)
									   FROM EMP
									   WHERE SAL < (SELECT MAX(SAL)
													FROM EMP))));

--63. WAQTD NAME OF THE EMPLOYEE EARNING 3RD MAXIMUM SALARY
SELECT ENAME 
FROM EMP
WHERE SAL < (SELECT MAX(SAL)
			FROM EMP
			WHERE SAL < (SELECT MAX(SAL)
						FROM EMP
						WHERE SAL < (SELECT MAX(SAL)
								FROM EMP )));
USE EMP;

--64.WAQTD EMPNO OF THE EMPLOYEE EARNING 2D MAXIMUM SALARY
SELECT EMPNO
FROM EMP
WHERE SAL < (SELECT MAX(SAL)
					FROM EMP
					WHERE SAL < (SELECT MAX(SAL)
								FROM EMP));

--65. WAQTD DEPARTMENT NAME OF AN EMPLOYEE GETTING 4TH MAX SAL
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO
				FROM EMP
				WHERE SAL < (SELECT MAX(SAL)
							 FROM EMP
							 WHERE SAL < (SELECT MAX(SAL)
										  FROM EMP
										  WHERE SAL < (SELECT MAX(SAL)
													   FROM EMP
													   WHERE SAL < (SELECT MAX(SAL)
																	FROM EMP)))));

--66. WAQTD DETAILS OF THE EMPLOYEE WHO WAS HIRED 2nd 
SELECT *
FROM EMP
WHERE HIREDATE  IN (SELECT MIN(HIREDATE)
					FROM EMP
					WHERE HIREDATE > (SELECT MIN(HIREDATE)
									  FROM EMP));

--67.WAQTD NAME OF THE EMPLOYEE HIRED BEFORE THE LAST EMPLOYEE
SELECT ENAME
FROM EMP
WHERE HIREDATE = (SELECT MAX(HIREDATE)
				FROM EMP
				WHERE HIREDATE < (SELECT MAX(HIREDATE)
								FROM EMP ));

--68. WAQTD LOC OF THE EMPLOYEE WHO WAS HIRED FIRST
SELECT LOC
FROM EMP
WHERE HIREDATE = (SELECT MIN(HIREDATE)
				 FROM EMP);

--69. WAQTD DETAILS OF THE EMPLOYEE EARNING 7TH MINIMUM SALARY
SELECT *
FROM EMP
WHERE SAL = (SELECT MIN(SAL)
			FROM EMP
			WHERE SAL > (SELECT MIN(SAL) 
						FROM EMP
						WHERE SAL > (SELECT MIN(SAL)
									FROM EMP
									WHERE SAL > (SELECT MIN(SAL)
												FROM EMP
												WHERE SAL > (SELECT MIN(SAL)
															 FROM EMP
															 WHERE SAL > (SELECT MIN(SAL)
																		  FROM EMP
																		  WHERE SAL > (SELECT MIN(SAL)
																					   FROM EMP)))))));

--70. WAQTD DNAME OF EMPLOYEE GETTING 2ND MAXIMUM SALARY
SELECT DNAME
FROM EMP
WHERE SAL = (SELECT MAX(SAL)
			 FROM EMP
			 WHERE SAL < (SELECT MAX(SAL)
						  FROM EMP));
--ASSIGNMENT ON EMP AND MANAGER RELATION .
USE EMP;

--71.WAQTD SMITHS REPORTING MANAGER'S NAME
SELECT ENAME
FROM EMP
WHERE EMPNO IN  (SELECT MGR
				FROM EMP
				WHERE ENAME = 'SMITH');

SELECT * FROM EMP;

--72.WAQTD ADAMS MANAGER'S MANAGER NAME
SELECT ENAME
FROM EMP
WHERE EMPNO IN ( SELECT MGR
				FROM EMP
				WHERE EMPNO = ( SELECT MGR
								FROM EMP
								WHERE ENAME = 'ADAMS'));


--73.WAQTD DNAME OF JONES MANAGER
SELECT DNAME
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO
				FROM EMP
				WHERE EMPNO IN ( SELECT MGR
								 FROM EMP
								 WHERE ENAME = 'JONES'));

--74.WAQTD MILLER'S MANAGER'S SALARY
SELECT SAL
FROM EMP
WHERE EMPNO = ( SELECT MGR
				FROM EMP
				WHERE ENAME = 'MILLER');

--75.WAQTD LOC OF SMITH'S MANAGER'S MANAGER.
SELECT LOC
FROM DEPT
WHERE DEPTNO IN ( SELECT DEPTNO
				  FROM EMP
				  WHERE MGR IN ( SELECT EMPNO
								 FROM EMP
								 WHERE EMPNO IN ( SELECT MGR
												  FROM EMP
												  WHERE ENAME = 'SMITH')));

--76.WAQT DNAME OF THE EMPLOYEES REPORTING TO BLAKE
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN ( SELECT DEPTNO
				 FROM EMP
				 WHERE MGR IN ( SELECT EMPNO
								FROM EMP
								WHERE ENAME = 'BLAKE'));


--77.WAQTD NUMBER OF EMPLPOYEES REPORTING TO KING
SELECT COUNT(*) AS KINGS_TEAM
FROM EMP
WHERE MGR IN ( SELECT EMPNO
			   FROM EMP
			   WHERE ENAME = 'KING');

--78.WAQTD DETAILS OF THE EMPLOYEES REPORTING TO JONES
SELECT *
FROM EMP
WHERE MGR IN ( SELECT EMPNO
			   FROM EMP
			   WHERE ENAME = 'JONES');

--79.WAQTD ENAMES OF THE EMPLOYEES REPORTING TO BLAKE'S MANAGER
SELECT ENAME 
FROM EMP
WHERE MGR IN ( SELECT EMPNO
			   FROM EMP
			   WHERE ENAME = 'BLAKE');

--80) NUMBER OF EMPLOYEES REPORTING TO FORD'S MANAGER
SELECT COUNT(*) "FORDS TEAM"
FROM EMP
WHERE MGR IN ( SELECT EMPNO
			   FROM EMP
			   WHERE ENAME = 'FORDS');

--ASSIGNMENT ON INNER JOINS  OR NATURAL JOIN 

--131) WAQTD ENAME AND DNAME FOR ALL THE EMPLOYEES ?
SELECT ENAME , DNAME 
FROM EMP , DEPT;

--132) WAQTD DNAME AND SAL FOR THE EMPLOYEES WHO ARE WORKING AS MANAGER ?
SELECT DNAME , SAL
FROM EMP , DEPT
WHERE JOB = 'MANAGER';

--133) WAQTD SAL AND HIREDATE AND LOC FOR THE EMPLOYEES WHOSE NAME HAVING A CHARACTER IN THEIR NAME  ?
SELECT SAL , HIREDATE , LOC
FROM EMP , DEPT
WHERE ENAME LIKE '%A%';

--134) WAQTD ALL THE DETAILS OF AN EMPLOYEE ALONG WITH LOC FOR AN EMPLOYEES  WHOSE SAL IS MORE THEN 2000 IN ACCOUNTING DEPARTMENT ?
SELECT *
FROM EMP E , DEPT D
WHERE SAL > 2000 AND E.DEPTNO IN (SELECT DEPTNO D
								FROM DEPT
								WHERE DNAME = 'ACCOUNTING');

--135) WAQTD DNAME AND SAL AND DEPTNO OF AN EMPLOYEES WHOSE JOB IS PRESIDENT  IN DEPTNO 10 ?
SELECT DNAME , SAL , E.DEPTNO
FROM EMP E , DEPT D
WHERE JOB = 'PRESIDENT' AND E.DEPTNO = 10;

--136) WAQTD ENAME AND DEPTNO AND LOC FOR ALL THE EMPLOYEES WHOSE NAME ENDS  WITH VOWELS ?
SELECT ENAME , E.DEPTNO , LOC
FROM EMP E , DEPT D
WHERE ENAME LIKE '%A' AND ENAME LIKE '%E' AND ENAME LIKE '%I' AND ENAME LIKE '%O' AND ENAME LIKE '%U';

--137) WAQTD HIREDATE AND DEPTNO FOR ALL THE EMPLOYEES WHO ARE WORKING IN  NEW YORK AND HAVING COMM ?
SELECT HIREDATE , D.DEPTNO 
FROM EMP E , DEPT D
WHERE E.DEPTNO = D.DEPTNO AND COMM IS NULL AND E.DEPTNO IN (SELECT D.DEPTNO
														    FROM DEPT
															WHERE LOC = 'NEW YORK');

--138) WAQTD EMPLOYEE NAME AND DEPARTMENT NAME FOR ALL THE EMPLOYEE WHO  ARE HIRED IN THE MONTH OF FEB INTO ACCOUNTING  DEPARTMENT ?
SELECT ENAME , DNAME 
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO AND HIREDATE LIKE '%FEB%' AND E.DEPTNO = (SELECT D.DEPTNO
																	FROM DEPT
																	WHERE LOC = 'ACCOUNTING');

--139) WAQTD LOC AND EMPNO AND MGR NO FOR ALL THE EMPLOYEES WHOSE SAL LESS THEN 5000 IN BOSTON HIRED IN THE YEAR OF 87 ?
SELECT LOC , EMPNO , MGR
FROM EMP E , DEPT D
WHERE SAL < 5000 AND HIREDATE BETWEEN '01-JAN-1987' AND '31-DEC-1987' AND E.DEPTNO IN (SELECT D.DEPTNO
																					 FROM DEPT
																					 WHERE LOC = 'BOSTON');

--140) WAQTD DNAME AND LOC ALONG WITH 10% HIKE IN THE SALARY OF AN EMPLOYEE WHO ARE REPORTING TO ALLEN ?
SELECT DNAME , LOC , (SAL + SAL *10/100) AS ASAL
FROM EMP E , DEPT D
WHERE MGR IN (SELECT EMPNO
			  FROM DEPT 
			  WHERE ENAME = 'ALLEN');

--141) WAQTD ANNAUL SALARY AND LOC OF AN EMPLOYEE WHOSE MANAGER NAME IS KING ?
SELECT SAL * 12 AS ASAL
FROM EMP E , DEPT D
WHERE EMPNO IN (SELECT MGR
				FROM DEPT
				WHERE ENAME  = 'KING');

--142) WAQTD ALL TEH DETAILS OF AN EMPLOYEES AND THEIR DNAME AND  LOC  FOR THE EMPLOYEE WHOSE COMM IS NULL IN DEPTNO 10,20  ?
SELECT *
FROM EMP E , DEPT D
WHERE COMM IS NULL AND D.DEPTNO IN (10,20);

--143) WAQTD DNAME AND ENAME FOR THE EMPLOYEE WHOSE SALARY ENDS WITH 50  IN DEPTNO 10,20,30 AND WORKING IN RESEARCH DEPARTMENT ?
SELECT DNAME , ENAME 
FROM EMP E , DEPT D
WHERE SAL LIKE '%50' AND D.DEPTNO IN (10,20,30);

--144) WAQTD LOC DNAME  AND ENAME OF AN EMPLOYEES WHO ARE HIRED BEFORE THE LAST TWO EMPLOYEES ?
SELECT LOC , DNAME , ENAME
FROM EMP E , DEPT D
WHERE 

--145) WAQTD DNAME AND SALARY OF AN EMPLOYEE WHOSE NAME ENDS WITH CONSONANTS ?
SELECT DNAME , SAL
FROM EMP NATURAL JOIN DEPT
WHERE ENAME NOT LIKE '%A' 
AND ENAME NOT LIKE '%E' 
AND ENAME NOT LIKE '%I' 
AND ENAME NOT LIKE '%O' 
AND ENAME NOT LIKE '%U';

--146) WAQTD MGR SAL AND DEPTNO AND LOC OF AN EMPLOYEES WHOSE LOC ENDS WITH S ?
SELECT MGR , SAL , DEPTNO , LOC
FROM EMP NATURAL JOIN DEPT
WHERE DEPTNO = (SELECT DEPTNO
				FROM DEPT
				WHERE LOC LIKE '%S');
SELECT * FROM EMP;
USE EMP;

--147) WAQTD EMPNO AND LOC FOR THE EMPLOYEES WHOSE HIREDATE IS '01-JAN-81' IN DALLAS ?
SELECT EMPNO , LOC 
FROM EMP NATURAL JOIN DEPT
WHERE HIREDATE = '01-JAN-81' AND DEPTNO IN (SELECT DEPTNO
											FROM DEPT
											WHERE LOC = 'DALLAS');

--148) WAQTD ENAME AND LOC AND SAL OF AN EMPLOYES WHOSE EMPNO ARE 7369,7488 ?
SELECT ENAME , LOC , SAL
FROM EMP NATURAL JOIN DEPT
WHERE EMPNO  IN(7369 , 7488);

--149) WAQTD ENAME AND LOC FOR THE EMPLOYEES WHOSE SAL IS LESS THEN KING AND MORE THEN SMITH IN DEPTNO 30 AND WORKING IN SALES DEPARTMENT ?
SELECT ENAME , LOC
FROM EMP NATURAL JOIN DEPT
WHERE SAL < (SELECT SAL
			 FROM EMP
			 WHERE ENAME = 'KING') AND SAL > (SELECT SAL
											  FROM EMP
											  WHERE ENAME = 'SMITH');

--150) WAQTD COMM AND LOC FOR THE EMPLOYEES WHOSE MGR IS 7902 WORKING IN ACCOUNTING AND RESEARCH DEPARTMENT ?
SELECT COMM , LOC
FROM EMP NATURAL JOIN DEPT
WHERE MGR = 7902 AND DEPTNO IN (SELECT DEPTNO
								FROM DEPT
								WHERE DNAME IN ('ACCOUNTING' , 'RESEARCH'));
USE EMP;

--211) WAQTD THE NO OF CHARACTERS PRESENT IN YOUR NAME ?
 select length('pranoti') from dual;

--212) WAQTD THE DEATILS OF THE EMPLOYEES WHOSE NAME HAVING 4 CHARACTERS ?
SELECT SUBSTR(ENAME , 4) FROM EMP;

213) WAQTD ENAME AND LOC OF ALL THE EMPLOYEES WHO ARE EARNING 4 DIGIT OF SALARY ?
214) WAQT GET THE REMINDER VALUES OF 10 /5 ?
SELECT MOD(10/5) FROM 
215) WAQTD THE DEATILS OF EMPLOYEES WHOSE NAME ENDS WITH VOWELS ?
216) WAQTD ALL THE DEATILS OF THE EMPLOYEES WHO AHEV MORE THEN 513 MONTHS 
   OF EXPERIANCE ?
217) WAQT REPLACE THE 3RD A FROM THE MALAYALAM ?
218) WAQTD THE FIRST HALF NAME OF EMPLOYEES SAME AND 2ND HALF NAME 
   OF EMPLOYEES IN REVERSE MANNAER ?
219) WAQT REPLACE THE FIRST 6 NUMBER AS (*) FROM 9900199001 ?
220) WSQTD OF THE EMPLOYEES WHOSE NAME HAVING EXACTLY 2 A IN THEIR NAMES ?
221) WAQTD DNAME AND SAL OF ALL THE EMPLOYEES WHOSE NAMES ARE PALYDROM IN NATURE ?
222) WAQTD DNAME AND ENAME OF ALL THE EMPLOYEES WHOSE 2ND HALF NAME PALYDROM IN NATURE ?
223) WAQTD THE TOTAL SALARY NEEDED TO PAY FOR EACH AND EVERY EMPLOYEES ?(NVL)
224) WAQTD THE DETAILS OF THE EMPLOYEES WHO ARE EARNING 3RD MAX SALARY FROM EMP TABLE ?
225) WAQTD THE 2ND MAX SALARY FROM EACH AND EVERY JOB ?
226) WAQTD THE EMPLOYEES NAME AND THEIR DNAME IN INITCAP FORMAT 
    AND ALSO DISPLAY THEIR JOB IN LOWER CASE FORMAT ?
227) WAQT GET THE NO OF MONTHS BETWEEN YOUR DATE OF BIRTH TO TODAYS DATE ?
228) WAQT GET THE YOUR CURRENT AGE IN YEAR FORMAT UPTO THE DATE ?
229) WAQT CONCAT ENAME WITH THEIR  HALF DNAME OF ALL THE EMPLOYEES ?
230) WAQT GET THE DEATILS OF THE EMPLOYEES IF THEIR NAME HAVING % AS LAST LETTER ?
231) WAQTD THE DETAILS OF AN EMPLOYEES IF THEIR SALARIES ARE PALYDROM IN NATURE ?
232) WAQTD ALL THE EMPLOYEES IF THEIR NAME AND DNAME STARST WITH SAME LETTER ?
233) WAQTD ALL THE EMPLOYEES IF THEIR NAME AND DNAME STARST AND ENDS WITH SAME LETTER ?
234) WAQTD THE LOC AND DNAME AND JOB OF ALL THE EMPLOYEES IF THEIR NAME MIDDLE 
    LETTERS ARE VOWELS ?
235) WAQT GET EXACTLY THE MIDDLE NAME FROM  "VIRAT ANUSKHA KHOLI" ?
236) WAQT PRINT THE DEATILS IN GIVEN FLOW 
    "HI SMITH GOOD MORNING YOUR DESIGNATION IS CLERK AND SALARY IS 800 YOUR 
    DEPTNO IS 20"  SAME FORMAT FOR ALL THE EMPLOYEES  ?
237) WAQTD ALL THE DETAILS OF THE EMPLOYEES WHO ARE HIRED ON WENSEDAY ?
238) WAQTD ALL THE DEATILF OF EMPLOYEES AND THEIR DEPARTMENT IF THEY ARE 
    HIRED IN THE MONTH OF DEC , JAN , FEB ?
239) WAQTD ALL THE EMPLOYEES IF THEY ARE HIRED IN THE YEAR OF 81, 87, 82 ?
240) WAQT GET THE YOUR CURRENT AGE WITH DAY OF BORN ?












